### ISSUE TITLE
The grave accent in markdown looks weird

### ISSUE THREAD

**Issue by tomtobac** [twilio/twilio-sans-mono#2]
Hey there 👋 

I love the new font 😍, especially the curly brackets! Recently I saw a weird display in markdown using VSCode with Windows 10.
Is this the expected display? Or I am having 

![image](https://user-images.githubusercontent.com/10562610/200636719-674dfacb-932b-4276-b496-a40a7405746f.png)

Thank you

**Comment by dkundel** [comment]
Hey @tomtobac try out the new version we just uploaded that should fix this issue :)
